/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#393939",
        "on-secondary-container": "#b4b5b7",
        "tertiary-container": "#007e3e",
        "on-secondary-fixed-variant": "#454749",
        "tertiary-fixed": "#62ff96",
        "on-surface": "#e5e2e1",
        "primary-container": "#2e5bff",
        "error-container": "#93000a",
        "surface-variant": "#353534",
        "on-surface-variant": "#c4c5d9",
        "surface-container-highest": "#353534",
        "error": "#ffb4ab",
        "surface-tint": "#b8c3ff",
        "on-secondary": "#2f3133",
        "on-tertiary": "#003918",
        "surface-container-lowest": "#0e0e0e",
        "inverse-on-surface": "#313030",
        "secondary-fixed": "#e2e2e5",
        "secondary-container": "#454749",
        "on-error": "#690005",
        "background": "#131313",
        "tertiary-fixed-dim": "#00e475",
        "surface": "#131313",
        "on-primary": "#002388",
        "on-tertiary-fixed": "#00210b",
        "surface-dim": "#131313",
        "on-tertiary-container": "#c1ffca",
        "on-primary-fixed": "#001356",
        "outline": "#8e90a2",
        "secondary-fixed-dim": "#c6c6c9",
        "surface-container": "#201f1f",
        "on-error-container": "#ffdad6",
        "outline-variant": "#434656",
        "inverse-surface": "#e5e2e1",
        "primary-fixed-dim": "#b8c3ff",
        "on-background": "#e5e2e1",
        "inverse-primary": "#124af0",
        "on-primary-fixed-variant": "#0035be",
        "primary": "#b8c3ff",
        "secondary": "#c6c6c9",
        "surface-container-low": "#1c1b1b",
        "tertiary": "#00e475",
        "surface-container-high": "#2a2a2a",
        "on-tertiary-fixed-variant": "#005226",
        "primary-fixed": "#dde1ff",
        "on-secondary-fixed": "#1a1c1e",
        "on-primary-container": "#efefff"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
