/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#1C2130",
        "on-secondary-container": "#B8C0CF",
        "tertiary-container": "#0F4A2C",
        "on-secondary-fixed-variant": "#454749",
        "tertiary-fixed": "#62ff96",
        "on-surface": "#EEF0F4",
        "primary-container": "#3B6CFF",
        "error-container": "#93000a",
        "surface-variant": "#171B24",
        "on-surface-variant": "#B8C0CF",
        "surface-container-highest": "#171B24",
        "error": "#FF8A80",
        "surface-tint": "#8FA8FF",
        "on-secondary": "#2f3133",
        "on-tertiary": "#003918",
        "surface-container-lowest": "#07090C",
        "inverse-on-surface": "#313030",
        "secondary-fixed": "#e2e2e5",
        "secondary-container": "#1C2130",
        "on-error": "#690005",
        "background": "#0A0C10",
        "tertiary-fixed-dim": "#35D07F",
        "surface": "#0A0C10",
        "on-primary": "#002388",
        "on-tertiary-fixed": "#00210b",
        "surface-dim": "#0A0C10",
        "on-tertiary-container": "#c1ffca",
        "on-primary-fixed": "#001356",
        "outline": "#5B6478",
        "secondary-fixed-dim": "#c6c6c9",
        "surface-container": "#0F1218",
        "on-error-container": "#ffdad6",
        "outline-variant": "#262B36",
        "inverse-surface": "#EEF0F4",
        "primary-fixed-dim": "#8FA8FF",
        "on-background": "#EEF0F4",
        "inverse-primary": "#124af0",
        "on-primary-fixed-variant": "#0035be",
        "primary": "#8FA8FF",
        "secondary": "#9AA3B2",
        "surface-container-low": "#0D1016",
        "tertiary": "#35D07F",
        "surface-container-high": "#11141B",
        "on-tertiary-fixed-variant": "#005226",
        "primary-fixed": "#dde1ff",
        "on-secondary-fixed": "#1a1c1e",
        "on-primary-container": "#FFFFFF",
        "muted": "#9AA3B2",
        "accent": "#3B6CFF",
        "accent-hover": "#4F7BFF",
        "accent-soft": "#8FA8FF",
      },
      fontFamily: {
        "headline": ["'Instrument Serif'", "Georgia", "serif"],
        "body": ["Manrope", "system-ui", "sans-serif"],
        "label": ["'JetBrains Mono'", "ui-monospace", "monospace"]
      },
      borderRadius: {"DEFAULT": "0.375rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
      maxWidth: { "content": "1240px" },
    },
  },
  plugins: [],
}
